name: haxchange 
version: 0.0.1
synopsis: Cryptocurrency Exchange E-DSL
description: See README at <https://github.com/McGizzle/haxchange#readme>
maintainer: Sean McGroarty <mcgroas@tcd.ie>
license: BSD3
github: McGizzle/haxchange
category: Web
extra-source-files:
  - README.md

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wredundant-constraints -Wincomplete-uni-patterns -fno-warn-orphans 

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - wreq
  - connection
  - http-client-tls
  - http-client
  - lens
  - lens-aeson
  - aeson
  - containers
  - text
  - time
  - split
  - bytestring
  - base64-bytestring
  - base16-bytestring
  - cryptohash-sha512
  - cryptohash-sha256
  - ghc
  - unordered-containers
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Haxchange
    - Haxchange.Types
    - Haxchange.Utils
    - Haxchange.Bittrex.Api
    - Haxchange.Kraken.Api
    - Haxchange.Binance.Api

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - base >= 4.10 && < 5
      - haxchange
      - hspec
      - hspec-expectations
